/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedContaPedidosRouteImport } from './routes/_authenticated/conta.pedidos'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContaPedidosRoute =
  AuthenticatedContaPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedContaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conta': typeof AuthenticatedContaRouteWithChildren
  '/conta/pedidos': typeof AuthenticatedContaPedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conta': typeof AuthenticatedContaRouteWithChildren
  '/conta/pedidos': typeof AuthenticatedContaPedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/conta': typeof AuthenticatedContaRouteWithChildren
  '/_authenticated/conta/pedidos': typeof AuthenticatedContaPedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reset-password' | '/conta' | '/conta/pedidos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reset-password' | '/conta' | '/conta/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/_authenticated/conta'
    | '/_authenticated/conta/pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta/pedidos': {
      id: '/_authenticated/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof AuthenticatedContaPedidosRouteImport
      parentRoute: typeof AuthenticatedContaRoute
    }
  }
}

interface AuthenticatedContaRouteChildren {
  AuthenticatedContaPedidosRoute: typeof AuthenticatedContaPedidosRoute
}

const AuthenticatedContaRouteChildren: AuthenticatedContaRouteChildren = {
  AuthenticatedContaPedidosRoute: AuthenticatedContaPedidosRoute,
}

const AuthenticatedContaRouteWithChildren =
  AuthenticatedContaRoute._addFileChildren(AuthenticatedContaRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
